#!/usr/bin/bash

BASE_PROP_LOC="/var/lib/waydroid/waydroid_base.prop"

if [ "$1" = "enable_ff" ]; then
  echo persist.waydroid.multi_windows=true >> "$BASE_PROP_LOC"
elif [ "$1" = "disable_ff" ]; then
  sed -i "/persist.waydroid.multi_windows=true/d" "$BASE_PROP_LOC"
elif [ "$1" = "disable_nav" ]; then
  echo qemu.hw.mainkeys=1 >> "$BASE_PROP_LOC"
elif [ "$1" = "kb_status" ]; then
  echo "pm list packages -d 2>/dev/null | grep com.android.inputmethod.latin | wc -l" | waydroid shell
elif [ "$1" = "enable_nav" ]; then
  sed -i "/qemu.hw.mainkeys=1/d" "$BASE_PROP_LOC"
else
  $1
fi
